### ISSUE TITLE
Time to update the description on docs.fp.o?

### ISSUE THREAD

**Issue by funnelfiasco** [fedora-silverblue/silverblue-docs#115]
*This issue doesn't apply to this repo directly, but I'm opening it here for better visibility*

The [front page of docs.fedoraproject.org](https://docs.fedoraproject.org/en-US/docs/) has the following description of Silverblue:

> Silverblue is the new face of Fedora Atomic Workstation from Project Atomic

Given that it's been a few years since Silverblue was new, we should probably find better wording. We don't need to rely on the Atomic name recognition anymore. I'm happy to make the edits or merge a PR to the [repo](https://pagure.io/fedora-docs/pages) once the team has picked new text.

**Comment by travier** [comment]
This has been updated.
