### ISSUE TITLE
Possible to download a local copy of this user manual as a PDF or markdown archive?

### ISSUE THREAD

**Issue by JaneSmith** [fedora-silverblue/silverblue-docs#120]
Hello. I was just wondering if it's possible to download a local copy of this user manual? Preferably in PDF format, or as a collection of markdown files. It doesn't seem to have any released files, and as far as I can tell is only available online as a website. Thanks.

**Comment by tpopela** [comment]
Closing this repository and going to https://github.com/fedora-silverblue/silverblue-docs/tree/master/modules/ROOT/pages isn't sufficient?

**Comment by travier** [comment]
You can build this repository locally and display it in a browser. Or you can use any tools to aspire the site into PDFs or something else.

Closing as we're not planning to work on this.
