### ISSUE TITLE
The Process of Making Article as an Official Documentation 

### ISSUE THREAD

**Issue by Harnapazade** [fedora-silverblue/silverblue-docs#121]
Hey guys I hope you are fine.I wrote an article in Fedora Magazine few days ago. I want to make this article [as a whole or some part of it] as an official Fedora Silverblue and Kinoite official documentation. How can I help?

https://fedoramagazine.org/how-i-customize-fedora-silverblue-and-fedora-kinoite/

**Comment by travier** [comment]
This is great! We have an in-progress, soon merged Tips & Tricks page in https://github.com/fedora-silverblue/silverblue-docs/pull/119. Once we have that, you can expand the page or create an other one. Feel free to make PRs here.

Don't worry to much about de-duplicating with Kinoite for now. I'll sync the doc changes with Kinoite as neeeded.

**Comment by Harnapazade** [comment]
Ok. I am waiting your return as soon as possible.

**Comment by travier** [comment]
We've merged the PR mentioned above. Feel free to send PRs!

**Comment by Harnapazade** [comment]
Hi there in order I can send Pull request first I need to fork and change files into the documentation and compare right? I am really new at Github so I need a little help here.

**Comment by Harnapazade** [comment]
> We've merged the PR mentioned above. Feel free to send PRs!

Hi there in order I can send Pull request first I need to fork and change files into the documentation and compare right? I am really new at Github so I need a little help here.

**Comment by travier** [comment]
Yes, you need a fork and then edit files and then push to your fork, etc. You should be able to follow any Git / GitHub guide to help you there.

**Comment by travier** [comment]
Closing as there is nothing to do here. Feel free to send PRs with more tips.
