### ISSUE TITLE
Update installation guide for Silverblue 30

### ISSUE THREAD

**Issue by rugk** [fedora-silverblue/silverblue-docs#18]
https://docs.fedoraproject.org/en-US/fedora-silverblue/installation-dual-boot/ still says "Silverblue 29"…

**Comment by dyoungwd** [comment]
I have sent a pull request to update Installation Guide and Installation:Dual Boot

**Comment by returntrip** [comment]
@miabbott This link is not in the repo anymore. Perhaps this issue can be closed?

**Comment by rugk** [comment]
But now no dual boot installation guide for Silverblue 30 is there anymore. So is this not supported/suggested anymore or what?

**Comment by returntrip** [comment]
@rugk It seems that page was removed on this [commit](https://github.com/fedora-silverblue/silverblue-docs/pull/22/files#diff-9c6c942e9ef0822a5fb8b7c0e77ac2f5).

I am not sure why tho :(.

**Comment by miabbott** [comment]
> @rugk It seems that page was removed on this [commit](https://github.com/fedora-silverblue/silverblue-docs/pull/22/files#diff-9c6c942e9ef0822a5fb8b7c0e77ac2f5).
> 
> I am not sure why tho :(.

Those instructions were originally based on SB28 (maybe even older) and were never really fool-proof to begin with.

If folks have a desire for these kind of instructions, we can bring them back, but I'd like to see them more polished than what was there before.  

Dual-booting should be supported just as we would support dual-booting with Fedora Workstation + another OS.  My understanding (and I could be wrong) is that dual booting with SB + another OS was never thoroughly tested, so there may be gremlins.

**Comment by tpopela** [comment]
Christian Kellner from the Red Hat's Hardware Enablement Team (that takes care of bootloaders as well) should look into dual boot stuff and hopefully streamline it a bit.

**Comment by rugk** [comment]
Should we possibly open a new issue for that feature?
