### ISSUE TITLE
Update Fedora Silverblue 30 release notes

### ISSUE THREAD

**Issue by rugk** [fedora-silverblue/silverblue-docs#19]
https://docs.fedoraproject.org/en-US/fedora-silverblue/f29-release-notes/

**Comment by allanday** [comment]
Personally speaking, it's a bit unclear what the purpose of the release notes are. The existing notes seem to mostly be a troubleshooting guide for people who are migrating from a previous version, but I think we're hoping that most F30 Silverblue users will be new.

Likewise, if we want to advertise the cool improvements and new features in F30, the documentation probably isn't the right place to do it.

**Comment by rugk** [comment]
I would be fine with deleting it or renaming it or so…

**Comment by returntrip** [comment]
@miabbott This link is not in the repo anymore. Perhaps this issue can be closed?
