### ISSUE TITLE
Local preview fails

### ISSUE THREAD

**Issue by allanday** [fedora-silverblue/silverblue-docs#20]
I'm currently working on the docs and followed the instructions in the readme to get them running locally. However, running `./build.sh && .preview.sh` results in the following error:

```
/usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint vigilant_mirzakhani (677b991551e51e5c8b6451b4dfc442460b0efdd59abab67e454d1f2394146399): Bind for 0.0.0.0:8080 failed: port is already allocated.
```
I'm running Fedora 29.

**Comment by returntrip** [comment]
@miabbott maybe this can be closed as we can now build and preview using `podman`? Also the error: `Bind for 0.0.0.0:8080 failed: port is already allocated` seems to imply that another service was using port `8080`.

**Comment by Saurabh-Thakre** [comment]
Closing the issue as it is unrelated on the context of the repository. Thanks @miabbott for the explanation.
