### ISSUE TITLE
Add an FAQ item about enabling Flash

### ISSUE THREAD

**Issue by allanday** [fedora-silverblue/silverblue-docs#28]
We had a query from someone on #silverblue about how to get Flash working in Firefox, so the chances are that other people are wondering the same thing.

It seems that the answer is to add the Adobe repo (see https://docs.fedoraproject.org/en-US/quick-docs/using-adobe-flash/ ) and then package-layer flash-plugin. This will work in the Firefox that's part of the OS image (probably not Flatpaked versions).

**Comment by Lailah** [comment]
Can we test this to see if it works on the flatpaked versions? I can setup a quick VM to see how it goes, if you want.
