### ISSUE TITLE
Add `podman` instructions for "Local preview" creation

### ISSUE THREAD

**Issue by returntrip** [fedora-silverblue/silverblue-docs#42]
Should I add a couple of lines to `README.md` about creating "Local previews" using `podman`?

**Comment by miabbott** [comment]
That would be a fine idea.

**Comment by asamalik** [comment]
I'm maintaining the Fedora Docs pipeline and I keep our [template repository](https://pagure.io/fedora-docs/template) updated with the newest instructions — including podman. Please feel free to just copy whatever is in there!

I'm usually not able to update all the repos we have. I'm wondering if there is an automated way we could do that?

**Comment by returntrip** [comment]
@asamalik I had update the scripts in my fork, then I looked at the Fedora Docs repo and saw that similar changes re: podman where already there.

I will create a frankenscript and publish here 😃.

I am interested in contributing a bit more formally to the FSB docs. I have joined the "fedora-docs" IRC channel to start with. Anything else I should do or be aware of?

**Comment by returntrip** [comment]
Closed via https://github.com/fedora-silverblue/silverblue-docs/pull/48
