### ISSUE TITLE
Description is too vague and not accessible to unfamiliar people

### ISSUE THREAD

**Issue by AMDphreak** [fedora-silverblue/silverblue-docs#5]
This article needs to be re-written from scratch.

https://docs.fedoraproject.org/en-US/fedora-silverblue/

Silverblue is defined in terms of other project names, keywords, and concepts, which are not previously explained in the article. For example, rpm-ostree is not something a potential reader would know about. This creates a circular dependency, requiring the reader to know one of the two before understanding the other.

A technical writer needs to be paid to make these understandable to technically-minded people who are unfamiliar with rpm-ostree.

**Comment by matthiasclasen** [comment]
> A technical writer needs to be paid to make these understandable to technically-minded people 

your donation will be welcome!

**Comment by AMDphreak** [comment]
I wouldn’t mind, but I am not figuring out what is already written. Hence the recommendation. I am technically-minded but not familiar with the project, its goals, its position in the software ecosystem, etc.

Ryan

**Comment by mrksu** [comment]
The linked article seems to have been rewritten, and the new version is no longer as heavy on technical jargon. I'd say it's quite well written now. Would it make sense to close this issue?

That said, if you still need a technical writer, I might volunteer or ask other people in the Red Hat documentation department.

**Comment by AMDphreak** [comment]
> The linked article seems to have been rewritten, and the new version is no longer as heavy on technical jargon. I'd say it's quite well written now. Would it make sense to close this issue?
> 
> That said, if you still need a technical writer, I might volunteer or ask other people in the Red Hat documentation department.

you got it boss
