### ISSUE TITLE
Silverblue Newbie dual boot issues

### ISSUE THREAD

**Issue by iandstanley** [fedora-silverblue/silverblue-docs#78]
I am new to silverlight but not to linux. Over the years I have done the usual distro wandering over the last 25 years from Slackware > SuSE > Debian > Redhat > RHEL > Debian > [MacOS] > [ChromeOS] > [ChromeOS with Debian] > Ubuntu > Debian > Fedora  > Debian (with a sideline of IoT with Raspbian)

I have an old lenovo thinkpad with an internal (/dev/sda) hard drive partitioned with a grub booter that handles the Debian (daily driver) & Windows 10 dual booting.

I have now added a 128gb SSD in the DVD bay and the other day decided to see how Fedora has progressed since I last used it. When I looked at the Fedora site I noticed silverblue and took to reading a little about it

Finding it technically interesting I decided to install a second drive (/dev/sdb) in my Thinkpad and installed silverblue to take it for a prolonged test drive to see if it would do me as a daily driver 

But I am having some issues sorting out grub booting.

The UEFI disabled bios sees both drives .... I can boot either drive via the choosing the drive via the bios menu interrupting the boot process manually.

However, try as I can I can't seem to get grub to see the drive 

I've added an entry as a type=Linux using grub-customizer pointing to /dev/sdb1 (ext4), /initd.img, /vmlinuz
boot sequence=
set root='(hd1,1)'
search --no-floppy --fs-uuid --set=root c36f613f-21ed-4ce0-896a-66492bca2487
linux /vmlinuz root=UUID=c36f613f-21ed-4ce0-896a-66492bca2487
initrd /initrd.img
grub-customizer saves and installs and then I reboot

When I reboot and select this option I can't boot silverblue.

I've also tried the same  options but pointing to the /dev/sdb2 LVM partition without any success.

 Newbire

**Comment by tpopela** [comment]
Hi @iandstanley do you still have the problems that you've described or you managed to install Silverblue?

**Comment by iandstanley** [comment]
managed to get it installed in the end thanks
